from .func_factor import (
    rq_get_factor,
    rq_get_factor_exposure,
    rq_get_instrument_industry,
    rq_get_price,
    rq_get_shares,
    rq_index_weights_ex,
    rq_is_st_stock,
    rq_is_suspended,
)
from .func_info import rq_all_instruments, rq_get_trading_dates

# RQData API配置
INFO_CONFIG = {
    "stock": {
        "func": rq_all_instruments,
        "params": {"type": "CS"},
    },
    "fund": {
        "func": rq_all_instruments,
        "params": {"type": "FUND"},
    },
    "futures": {
        "func": rq_all_instruments,
        "params": {"type": "Future"},
    },
    "option": {
        "func": rq_all_instruments,
        "params": {"type": "Option"},
    },
    "convertible": {
        "func": rq_all_instruments,
        "params": {"type": "Convertible"},
    },
    "etf": {
        "func": rq_all_instruments,
        "params": {"type": "ETF"},
    },
    "lof": {
        "func": rq_all_instruments,
        "params": {"type": "LOF"},
    },
    "tradedays": {
        "func": rq_get_trading_dates,
        "params": {},
    },
}

# Factor配置
FACTOR_CONFIG = {
    "default": rq_get_factor,
    "pe_ratio": rq_get_factor,
    "pb_ratio": rq_get_factor,
    "ps_ratio": rq_get_factor,
    # ST
    "is_st": rq_is_st_stock,
    # 停牌
    "is_paused": rq_is_suspended,
    # 行业
    "citics_2019_l1": rq_get_instrument_industry,
    "citics_2019_l1_name": rq_get_instrument_industry,
    "citics_2019_l2": rq_get_instrument_industry,
    "citics_2019_l2_name": rq_get_instrument_industry,
    "citics_2019_l3": rq_get_instrument_industry,
    "citics_2019_l3_name": rq_get_instrument_industry,
    "citics_l1": rq_get_instrument_industry,
    "citics_l1_name": rq_get_instrument_industry,
    "citics_l2": rq_get_instrument_industry,
    "citics_l2_name": rq_get_instrument_industry,
    "citics_l3": rq_get_instrument_industry,
    "citics_l3_name": rq_get_instrument_industry,
    "sws_l1": rq_get_instrument_industry,
    "sws_l1_name": rq_get_instrument_industry,
    "sws_l2": rq_get_instrument_industry,
    "sws_l2_name": rq_get_instrument_industry,
    "sws_l3": rq_get_instrument_industry,
    "sws_l3_name": rq_get_instrument_industry,
    "hsi_l1": rq_get_instrument_industry,
    "hsi_l1_name": rq_get_instrument_industry,
    "hsi_l2": rq_get_instrument_industry,
    "hsi_l2_name": rq_get_instrument_industry,
    "hsi_l3": rq_get_instrument_industry,
    "hsi_l3_name": rq_get_instrument_industry,
    # 行情因子
    "open": rq_get_price,
    "high": rq_get_price,
    "low": rq_get_price,
    "close": rq_get_price,
    "volume": rq_get_price,
    "total_turnover": rq_get_price,
    "trading_date": rq_get_price,
    "last": rq_get_price,
    "prev_close": rq_get_price,
    "limit_up": rq_get_price,
    "limit_down": rq_get_price,
    "a1": rq_get_price,
    "a2": rq_get_price,
    "a3": rq_get_price,
    "a4": rq_get_price,
    "a5": rq_get_price,
    "b1": rq_get_price,
    "b2": rq_get_price,
    "b3": rq_get_price,
    "b4": rq_get_price,
    "b5": rq_get_price,
    "a1_v": rq_get_price,
    "a2_v": rq_get_price,
    "a3_v": rq_get_price,
    "a4_v": rq_get_price,
    "a5_v": rq_get_price,
    "b1_v": rq_get_price,
    "b2_v": rq_get_price,
    "b3_v": rq_get_price,
    "b4_v": rq_get_price,
    "b5_v": rq_get_price,
    "change_rate": rq_get_price,
    "num_trades": rq_get_price,
    "open_interest": rq_get_price,
    "prev_settlement": rq_get_price,
    "settlement": rq_get_price,
    "open_post": rq_get_price,
    "high_post": rq_get_price,
    "low_post": rq_get_price,
    "close_post": rq_get_price,
    "volume_post": rq_get_price,
    "total_turnover_post": rq_get_price,
    "open_pre": rq_get_price,
    "high_pre": rq_get_price,
    "low_pre": rq_get_price,
    "close_pre": rq_get_price,
    "volume_pre": rq_get_price,
    "total_turnover_pre": rq_get_price,
    # 风格因子
    "momentum": rq_get_factor_exposure,
    "beta": rq_get_factor_exposure,
    "book_to_price": rq_get_factor_exposure,
    "earnings_yield": rq_get_factor_exposure,
    "liquidity": rq_get_factor_exposure,
    "size": rq_get_factor_exposure,
    "residual_volatility": rq_get_factor_exposure,
    "non_linear_size": rq_get_factor_exposure,
    "leverage": rq_get_factor_exposure,
    "growth": rq_get_factor_exposure,
    # 流通股
    "total": rq_get_shares,
    "authorized_shares": rq_get_shares,
    "total_a": rq_get_shares,
    "not_hk_shares": rq_get_shares,
    "preferred_shares": rq_get_shares,
    "total_hk": rq_get_shares,
    "total_hk1": rq_get_shares,
    # 成分股权重
    "constituent_weight": rq_index_weights_ex,
}


FACTOR_EXTRA_PARAMS = {
    "rq_get_price": ["skip_suspended", "market"],
    "rq_get_factor_exposure": ["industry_mapping", "model", "market"],
    "rq_get_shares": ["market"],
}
